<?php

namespace Inndividuell\ContaoJobsExtension;


use Contao\Config;
use Contao\Input;

class ModuleJobList extends \Module
{
    protected $strTemplate = 'mod_inn_jobs_reader';
    public function generate()
    {

        return parent::generate(); // TODO: Change the autogenerated stub
    }

    protected function compile()
    {

    }

}
class_alias(ModuleJobList::class, 'ModuleJobList');
