<?php

namespace Inndividuell\ContaoJobsExtension;


use Contao\Config;
use Contao\Input;

class ModuleJobReader extends \Module
{
    protected $strTemplate = 'mod_inn_jobs_reader';
    public function generate()
    {
        if (!isset($_GET['items']) && isset($_GET['auto_item']) && Config::get('useAutoItem'))
        {
            Input::setGet('items', Input::get('auto_item'));
        }

        // Return an empty string if "items" is not set (to combine list and reader on same page)
        if (!Input::get('items'))
        {
            return '';
        }

        return parent::generate(); // TODO: Change the autogenerated stub
    }

    protected function compile()
    {
        // TODO: Implement compile() method.
        $foo = 'bar';
        $alias = Input::get('items');
        $this->Template->alias = $alias;
    }

}
class_alias(ModuleJobReader::class, 'ModuleJobReader');
