<?php

namespace Inndividuell\ContaoJobsExtension;


use Contao\Config;
use Contao\Input;
use Contao\PageModel;

class ModuleJobReader extends \Module
{
    protected $strTemplate = 'mod_inn_jobs_reader';
    public function generate()
    {
        if (!isset($_GET['items']) && isset($_GET['auto_item']) && Config::get('useAutoItem'))
        {
            Input::setGet('items', Input::get('auto_item'));
        }

        // Return an empty string if "items" is not set (to combine list and reader on same page)
        if (!Input::get('items'))
        {
            return '';
        }

        return parent::generate(); // TODO: Change the autogenerated stub
    }

    protected function compile()
    {
        // TODO: Implement compile() method.
        $foo = 'bar';
        $alias = Input::get('items');
        $back_page = $this->inn_jobsreader_back_link_page;
        $back_page_obj = PageModel::findByPk($back_page);
        $back_page_url  = $back_page_obj->getAbsoluteUrl();
        $back_page_text = $this->inn_jobsreader_back_link_text;
        $sql_string = "SELECT tl_inn_jobs.*,tl_inn_jobs_type.title as job_type_title FROM tl_inn_jobs  LEFT JOIN tl_inn_jobs_type ON tl_inn_jobs.job_type = tl_inn_jobs_type.id  WHERE tl_inn_jobs.published=1 AND alias='".$alias."'";
        $item = $this->Database->query($sql_string)->fetchAllAssoc()[0];
        $download_path = false;
        if($item['job_download']) {
            $file = \Contao\FilesModel::findByUuid($item['job_download']);
            if ($file !== null) {
                $download_path = $file->path;
            }
        }

        $this->Template->download_path = $download_path;
        $this->Template->alias = $alias;
        $this->Template->item = $item;
        $this->Template->back_url = $back_page_url;
        $this->Template->back_text = $back_page_text;

    }

}
class_alias(ModuleJobReader::class, 'ModuleJobReader');
